name: Build LaTeX CV and deploy it on GitHub Releases

on:
  push:
    tags: '*'
    branches-ignore:
      - 'autodelivery**'
      - 'bump-**'
      - 'renovate/**'
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'renovate.json'
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-open-sans
          wget -O Font-Awesome-6.4.0.tar.gz https://github.com/FortAwesome/Font-Awesome/archive/6.4.0.tar.gz
          tar -xvzf Font-Awesome-6.4.0.tar.gz
          cd Font-Awesome-6.4.0
          sudo mkdir -p /usr/share/fonts/opentype
          sudo mkdir -p /usr/share/fonts/truetype
          sudo cp otfs/*.otf /usr/share/fonts/opentype
          sudo cp webfonts/*.ttf /usr/share/fonts/truetype
          sudo fc-cache -fv
        
      - uses: yusancky/setup-typst@v2
        id: setup-typst
        with:
          version: 'v0.7.0'

      - name: build CV
        run: typst compile nicolasfarabegoli-cv-eng.typ

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: "*.pdf"

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV
      
      - name: Autotag
        id: autotag
        if: github.ref_name == 'master'
        run: |
          if ! git describe --tags --exact-match HEAD; then
            TENTATIVE_TAG="$(git describe)" || TENTATIVE_TAG="0.1.0-$(git log -n1 --date=format:'%Y-%m-%dT%H%M%S' --format=%cd)"
            git tag "$TENTATIVE_TAG" -m "$(message "$TENTATIVE_TAG")"
          fi
          echo "TAG=$(git describe --tags --exact-match HEAD)" >> $GITHUB_OUTPUT
      

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_name == 'master'
        with:
          name: "Release — ${{ steps.autotag.outputs.tag }}"
          files: "*.pdf"
